import type { NextPage } from 'next'
import Head from 'next/head'
import ToDo from '../src/components/ToDo'
import Waves from '../src/components/Waves'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header">
        <ToDo />
        <Waves />
      </div>
    </div>
  )
}

export default Home
